services:
  - type: web
    name: soulseer-web
    env: node
    buildCommand: npm install; npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SIGNING_SECRET
        sync: false
      - key: NEXT_PUBLIC_WEBRTC_ICE_SERVERS
        sync: false
      - key: NEXT_PUBLIC_SIGNALING_SERVER_URL
        sync: false